### ISSUE TITLE
OK screen, no volume

### ISSUE THREAD

**Issue by jhoogeboom** [fentas/docker-volume-davfs#2]
Following the readme, I get this OK, but no created volumes when I do:
`docker volume ls`
<img width="831" alt="screen shot 2018-02-23 at 16 48 27" src="https://user-images.githubusercontent.com/1828504/36602880-6f6383c0-18b9-11e8-9b14-2d4773fce943.png">

**Comment by fentas** [comment]
Where do you get `OK`?
Could you explain what you have done, so that I may be able to recreate this behavior?

**Comment by jhoogeboom** [comment]
all of this is on OSX Version 10.13.2 (17C88)

Sure, so I install the plugin and that seems to work:

```
docker plugin install fentas/davfs
Plugin "fentas/davfs" is requesting the following privileges:
 - network: [host]
 - mount: [/var/lib/docker/plugins/]
 - device: [/dev/fuse]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from fentas/davfs
60a0c44b5ea4: Download complete 
Digest: sha256:623bd2f914267f83eaba03591cbebc4517b2d3bedcc28f70b25c239e6931f356
Status: Downloaded newer image for fentas/davfs:latest
Installed plugin fentas/davfs
```

trying to connect with:

```
docker volume create -d fentas/davfs -o url=<https://jorisjh.stackstorage.com/remote.php/webdav/> -o username=<jorisjh> -o password=<redacted> -o uid=1000 -o gid=1000 davvolume
```

This is where I get the OK message, which I figured happens because of my terminal, it just goes to the URL. I left out the question mark because I thought it was a typo, but perhaps it's go-specific and used in parsing.

```
docker volume create -d fentas/davfs -o url=<https?://jorisjh.stackstorage.com/remote.php/webdav/> -o username=<jorisjh> -o password=<redacted> -o uid=1000 -o gid=1000 davvolume
```
output:
` zsh: no matches found: https?://jorisjh.stackstorage.com/remote.php/webdav/ `

removing trailing slash does not seem to work either

This is the path from the webdav provider:
<img width="667" alt="screen shot 2018-02-26 at 09 40 39" src="https://user-images.githubusercontent.com/1828504/36660742-85eebf20-1ad9-11e8-9330-e64f20bdfe84.png">

**Comment by fentas** [comment]
Normally this should happen:
```
$ docker volume create -d fentas/davfs -o url=https://jorisjh.stackstorage.com/remote.php/webdav/ -o username=jorisjh -o password=redacted -o uid=1000 -o gid=1000 davvolume
davvolume
$ 
```

The `<` `>` should only indicate placeholder and the `?` is there to indicate optional for the last char, meaning `http` or `https`. Sorry for the confusion, I will make this clearer.

Edit: The next step would be for example
```
$ docker run -it -v `davvolume:/mnt` alpine:3.6 sh
$ ls /mnt
```

**Comment by jhoogeboom** [comment]
Thanks for the info, works well now!
